### ISSUE TITLE
git push not working for me 

### ISSUE THREAD

**Issue by ibkvictor** [hishamhm/pull-request-tutorial#66]
zeek-Mac:pull-request-tutorial zeek$  git push --set-upstream origin fix-typo-python
remote: Permission to hishamhm/pull-request-tutorial.git denied to ibkvictor.
fatal: unable to access 'https://github.com/hishamhm/pull-request-tutorial.git/': The requested URL returned error: 403

**Comment by hishamhm** [comment]
You're almost there :) But yes, as the error message says, you can't push directly to my repo!

You need to fork the repo so that a copy of it appears in _your_ account, then `git clone` using your fork's URL, make changes and `git push` to it, and and then create the pull request from your repo back to mine! Hope that helps!
